menu:
  #Archives: /archives
#  黄金屋: /favourite
#  时光机: /favourite/time.html
  profile: https://resume.gemer.xyz
rss: /atom.xml
description: Design & Desert, Code & Enthusiasm, Think & Meaning in Life.
social:
  weibo:
  github: https://github.com/gemerz
  stack_overflow: 
  facebook: 
  twitter: https://twitter.com/gemerzhang
  google_plus: 

page_comment: false
logo: /images/logo.png
background:
  cover: linear-gradient(to top, #16222a, #3a6073)
  color: cover-green

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: 

google_analytics: 
favicon: /favicon.png

